import { TooltipProvider } from "@/components/ui/tooltip"
import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/ui/themes' // 1. Import the dark theme base
import { Poppins } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { Toaster } from "@/components/ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display:'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.className} antialiased text-slate-100 bg-slate-950`}>
      <ClerkProvider
  appearance={{
    theme: dark,
    variables: {
      colorPrimary: '#8b5cf6', // Vibrant Purple (violet-500) for active states/accents
    },
    elements: {
      // Main card container
      card: 
        "bg-[#0b0f19] border border-slate-800/80 shadow-xl shadow-purple-500/5 backdrop-blur-md text-slate-100",
        
        // Text color overrides
        headerTitle: "text-slate-100",
        headerSubtitle: "text-slate-400",
        formFieldLabel: "text-slate-300 font-medium",
        footerActionText: "text-slate-400",
        footerActionLink: "text-purple-400 hover:text-purple-300",
      
        // Input field styles
        formFieldInput: 
        "bg-slate-900 border-slate-800 text-slate-100 focus:border-purple-500 focus:ring-purple-500",
        
        // Social button styles (Google, GitHub, etc.)
        socialButtonsBlockButton:
        "bg-slate-900/50 border border-slate-800 hover:bg-slate-900 hover:border-purple-500/50 transition-all duration-200",
        
        socialButtonsBlockButtonText:
        "!text-slate-200 font-medium",
        
        socialButtonsProviderIcon:
        "opacity-100 filter drop-shadow-[0_0_4px_rgba(139,92,246,0.2)]",
      
      // Divider styles
      dividerLine:
        "bg-gradient-to-r from-transparent via-slate-800 to-transparent",
        
        dividerText:
        "text-slate-400 font-medium text-xs tracking-wider uppercase",
        
        // User Profile Button & Popover styles
        userButtonPopoverCard: 
        "bg-[#0b0f19] border border-slate-800/80 shadow-lg shadow-purple-500/5",
        
        userButtonPopoverActionButton:
        "text-slate-200 hover:bg-purple-950/30 hover:text-purple-300 transition-colors",
        
        userButtonPopoverActionButtonText:
        "!text-slate-200 group-hover:text-purple-300",
        
        userButtonPopoverFooter:
        "bg-[#070a10] border-t border-slate-800/80",
        
        // Primary Action Button styles (Sign In / Sign Up)
        formButtonPrimary: 
        "bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 transform active:scale-[0.98] transition-all text-white font-semibold shadow-md shadow-purple-500/10",
      },
    }}
>
          <Provider>
            <TooltipProvider>
              {children}
              <Toaster />
            </TooltipProvider>
          </Provider>
        </ClerkProvider>
  <Analytics/>
  <SpeedInsights/>
      </body>
    </html>
  )
}